### ISSUE TITLE
VIP的cookie不行

### ISSUE THREAD

**Issue by 1chenyx** [Beadd/Creamplayer#58]

**Comment by 1chenyx** [comment]
![image](https://github.com/Beadd/Creamplayer/assets/127660408/d5176aba-2963-4970-9b61-09027f3e3af6)

**Comment by 1chenyx** [comment]
![image](https://github.com/Beadd/Creamplayer/assets/127660408/63aab46f-e6b7-4233-920c-ed317e81850f)

**Comment by Beadd** [comment]
- 登录你的会员账号
- 然后把music.163.com的Cookie全部复制到程序里面就行了
![](https://raw.githubusercontent.com/Beadd/Creamplayer/main/images/cookie.png)

**Comment by 1chenyx** [comment]
![image](https://github.com/Beadd/Creamplayer/assets/127660408/74ab18d4-bf2c-4614-bbf7-7e3398c4a5d0)



__bid_n=1872b3668127e2d2794207; _ntes_nnid=54230625321c93358a6054b07eb478a2,1681131754935; _ntes_nuid=54230625321c93358a6054b07eb478a2; vjuids=101cace0e.187ae42d2a2.0.2f7a0b0bd4fd; vjlast=1682255828.1682255828.30; vinfo_n_f_l_n3=03f65e6a4f7e6a16.1.0.1682256266468.0.1682256274179; FPTOKEN=Ywx7jzrP/G7a61/lPREMW2X6UodjNL+CNGhHHJ+lsUdZJJ5dYvcgNcwdID5HAPHLxDkCo2ZpVL5UGFP3tpcn94KJHYSg/bTR+HQjizWmiohMjNe13qx1t3a0ILOUXFa6+LdIEsOP1znYhjRVRoSG8Yh6Q1/E5R/hK2jcKB93N2NVUZgtSJquEIMrx4i7hzOnk6JdDsG2rdQN2pnG7LHNz36Wr85iniOgxNP/CsalYycZ/iCfxqvZolah83QXA5HUbUHhb1Uaf9VkYGLir60e5Ur0zSZEtXsgNyj1Hj/gZy6IEWJJzB4rbopNbtnZVwy4rMmFFOmVqV9D5qFUgliXBLMTtfOxINJP5Qr/2TSL9WTJrPxRyQ4ELdsFBZHMpuC5c6hKKSszSjTPOLLXSqJfxw==|WcC5Xr79NxZrFJ3KQKPZXbrFk4mAeDMZOYVb988TJe4=|10|a34e5d1beee743a5f29a45403d6b5d9a; NMTID=00OrAOslFgXmW1o9UCUqUSG-89Kb7gAAAGJ6xahlw; _iuqxldmzr_=32; WEVNSM=1.0.0; WNMCID=lpprcl.1691866277600.01.0; WM_TID=5ujN2lAYGtlABRQQVBKE1LO3IM9xMMQI; ntes_utid=tid._.MQP31oJm8Q9FRhQRQAaVxKa2IY4waSTg._.0; sDeviceId=YD-d3HJ1xmCJwpEVlBFQAKAaTOAmroxpzYG; WM_NI=1Z6dgad2RYj1Msu9dx7d8Eme7vkMaKnCfLDKfybz6TCmEaVEdVDyo3GWE83CrCW2g4B2S0crRocCRr9a38LiQBDP19oVuDF1GVR5MBcSXX4lpNO8c6T4XfNVFRDIo2era0o%3D; WM_NIKE=9ca17ae2e6ffcda170e2e6ee98ee6d94f0c08ed160aebc8eb7d85a868f8f83c861b2b08b97e96e85b989b9ce2af0fea7c3b92af386fa85e66ba8ee9ebae93b8fadbbdae774f5bcf8a6f06ff5aaa5aee441ae9daaadc741a6a7ae9bb56081b38b82d54fa88a8c9aee3985898bd9b249b29d99d3e64082ee9dd1e27a92b1ada4d17afbbffdd9cf63939e8cb1b433ad8abba5c53b858a9ed6d04aa18d98b9b768b49281d9e23e98ec9887cd5e868e8caaee3aa7aeafd1ee37e2a3; __snaker__id=Nb0DDeHNpw2SxmuU; YD00000558929251%3AWM_NI=WgYVL1E8xw7iXVraW6plInAaX92Wrjh48x52xqzTj6DikDmDc%2BU8dZtRxV6thQWH1e7H3bWNBx7fnMA3Pq07BkT6UqI%2BY0ILhDol6KLLXFLBjgBucASYaKWImCp19L7yZkM%3D; YD00000558929251%3AWM_NIKE=9ca17ae2e6ffcda170e2e6eeadbc7298b1aab8d4419ab88ea7d55e939b8b82d461f6ec9eccf37382a9a599d22af0fea7c3b92a95b997b7cf3b87e8b898b6639c8abe82d63eb4b4878fc46b9ce7feb8f162acecf899b83abcafb6b5e93e88b7a5a5f050a1f59bd9e752b88eb8b7b580ac8f99a9b46ff598fd83d64682a8f987ed4783eda092b33d82b59cd7d87b8bf597d1cc48ac9ca18db541909498a7cf4aaab98e96e24b9187afacd643af9dc0d2bc48f5a7968cd037e2a3; YD00000558929251%3AWM_TID=fvfRmWrbgHNFUERBVAOE06sVu9jR01xT; ntes_kaola_ad=1; playerid=83636142; JSESSIONID-WYYY=nv28WIU7j34cxKOkBR1Gc%2FMTzOfQchuId870FHthnP%2BkDpCn%2B04u0k%2BFifvfFadRklcod517b8IJwKErmQ8GHKU5JS9VWX59lnpv78DJ3jI%2FcKYWwAR44zaPlO8GgGoIJWWTe%2BFOREKjPqpFqKCh%2FfYtNgPYIbSWV7OQhfRaZzB0PBcx%3A1691972045007; gdxidpyhxdE=onvXrksq%5Cbe%5CKzf7CLNNShmIzSoltJ2nYnls%5CTqroKSJzw3hQ6KY1ClHs3dpKz%2B7GpeWz%2FbcomrEmrhcmspdY%5Cho4VsUnScSy7Bb1StKAQ0LRGzaoJIextZ7I3bBia9qGxgDACyKDlxr5OiXDvP9PcyvDk7QM61jinXRehLPePIupBrz%3A1691971247892; MUSIC_U=002C150954286B06E4510E3D14B3C42533FE9B5EA2C1D0B12EC2D95A71104CAC79185FE5835C867C7F224633A58A750C31C879EE9D45584F12A9577BF96E259E4FC1C618A8AF80C1A97B38E7D2E69AC96DAB04E1066756BF0AF447D8F3DA73D027B090D350A5F3F35FBA171749E086947411E2FF69A26098A64A053EF145288099D5FB7BD65BE52CD2AF874D1E21B535170B71DDF7C8D9ED7F28EE7671D098D78EEDCDF7118973A18BE85EA2AA5B2CCA914E4A094202729CF70DB8E2E9346BB496F8E2003DF9A82D56AC7F7B1F1C3BCC51FFBAB7EDACA5C0F5FE0D314C48937074A7AB14D2357625B66E72E366AE04A819020C0E3D4FAFDFD665DF7102CDEE9CA97FE1D919DB34B0BF6AF6F1A150B791F1D5B555DB6BC1A499189A2949FDCE9D777315626FBE9C39615D25E1E6AFE9336F9FE6F6DF5E821F79D299FD7509D5523DD656C3A61C69F6FD3C7C4523EAF079E7E45C2333757A4F4D2D43359E39C6A6DA; __csrf=63a13a288a87c978ccf2fc798c925e40
还是不行

**Comment by Beadd** [comment]
要重启一下，然后再设一次。是个bug，正在修复

**Comment by Beadd** [comment]
你把消息里的Cookie删了把，会泄露隐私

**Comment by 1chenyx** [comment]
好，谢谢了

**Comment by Beadd** [comment]
已修复，见[v4.0.1](https://github.com/Beadd/Creamplayer/releases/tag/v4.0.1)
