### ISSUE TITLE
Win客户端VIP Cookie如何在程序里设置

### ISSUE THREAD

**Issue by maclai85** [Beadd/Creamplayer#59]
这个步骤不明白 可否赐教一下 感谢

**Comment by cya0401** [comment]
现在好像无法通过Readme中的方法来进行设置了，直接从黑色的1变成红色的1，进入不了“播放界面”

**Comment by Beadd** [comment]
实测可以正常设置和下载。设置Cookie的步骤Readme里有提及：搜索一首VIP歌曲，进入该歌曲的播放界面即可设置。注意是需要已经是VIP账户的Cookie

**Comment by cya0401** [comment]
再测试了一下，确实正常，直接搜索就可以用，在chrome中找到歌曲再粘贴链接过来无法跳转，已能正常下载
