### ISSUE TITLE
如何选择下载歌曲的音质

### ISSUE THREAD

**Issue by valves31** [Beadd/Creamplayer#60]
如何进行音质选择，输入完cookie了之后是只能下载无损音质了嘛？还想下载320kbps怎么办

**Comment by Beadd** [comment]
目前填完cookie只能下载无损，想要下载其他音质可以修改api里的参数，把2147483647改成320000即可下载tps://github.com/Beadd/Creamplayer/blob/main/src/api/index.js#L51

**Comment by Beadd** [comment]
已更新360k版本https://github.com/Beadd/Creamplayer/releases/tag/v4.0.2

**Comment by valves31** [comment]
> 目前填完cookie只能下载无损，想要下载其他音质可以修改api里的参数，把2147483647改成320000即可下载https://github.com/Beadd/Creamplayer/blob/main/src/api/index.js#L51

感谢大佬的回答，请问如何在应用里找到这个界面然后更改参数呢

**Comment by Beadd** [comment]
暂无选择音质的界面，会在下个版本里添加

**Comment by valves31** [comment]
> 感谢beadd
