### ISSUE TITLE
请教一下，有使用指南么？

### ISSUE THREAD

**Issue by alexya** [Beadd/Creamplayer#61]
无意中搜索找到的，看上去好像是下载网易云和QQ音乐的工具，可是看了半天，不知道如何使用。
我下载了EyeD3Music，打开界面，好像是需要填写API服务器地址？例如 `http://api.injahow.cn/meting/` 
如果不是 Netease or QQ vip， 是不是vip歌曲下载不了？如果需要下载，则需要自己搭建API服务器，填写vip cookie什么的？

**Comment by jakesparro** [comment]
作者 你好 请问一下那个VIPcookie在哪获得？ 填到哪里 不好意思理解力有点差 还请指点

**Comment by Beadd** [comment]
![image](https://github.com/Beadd/Creamplayer/assets/93070342/c4be646c-7a15-4805-91ba-10f9f399baad)
https://github.com/Beadd/Creamplayer/releases/tag/v4.0.2 electron版本的使用说明就在release里。搜索一首VIP歌曲，进入该歌曲的播放界面就会出来cookie填充框

**Comment by Jason-JP-Yang** [comment]
我没有VIP，在VIP歌曲的界面复制下来的Cookie一直不行
![image](https://github.com/Beadd/Creamplayer/assets/108601445/6ac8b9e4-632f-46cc-9108-2eb531e99b32)

**Comment by Beadd** [comment]
必须要用网易云VIP账号的cookie才行

> 我没有VIP，在VIP歌曲的界面复制下来的Cookie一直不行 ![image](https://private-user-images.githubusercontent.com/108601445/324201829-6ac8b9e4-632f-46cc-9108-2eb531e99b32.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxODYxMTUsIm5iZiI6MTcxNDE4NTgxNSwicGF0aCI6Ii8xMDg2MDE0NDUvMzI0MjAxODI5LTZhYzhiOWU0LTYzMmYtNDZjYy05MTA4LTJlYjUzMWU5OWIzMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyN1QwMjQzMzVaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTEzMTA5NmQ3MDY1NTYwZmVjZmIyMjEzMzA4ODE3YmVlNDcxNjA0OGVmZWQ0ZDA0MzM4MDhhNjM0YTA2YmY5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j-n0qhSLIDV8GwZ4GFR1v81pgCzPZC1jiWVr5PxmSOs)

**Comment by nyyjshcz** [comment]
请问怎么设置下载码率？

**Comment by Beadd** [comment]
> 请问怎么设置下载码率？

默认最高，下载那个360k的即可

**Comment by nyyjshcz** [comment]
可是我没有看到选项欸，复制链接回车直接就下载了
![Screenshot 2024-11-04 160909](https://github.com/user-attachments/assets/a65cd917-7f2b-4e59-bc75-7c71d5dbbcfb)

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
