### ISSUE TITLE
你好新年快乐。歌单里歌曲下载数量对不上

### ISSUE THREAD

**Issue by valves31** [Beadd/Creamplayer#63]
歌单里有1937首歌，打开下载文件夹查看只有1494首，继续下载显示success，但文件夹1494数量不变，求解答.

**Comment by valves31** [comment]
![Uploading image.jpg…]()

**Comment by valves31** [comment]
反复下载之后文件夹里面的歌曲数量依旧没涨

**Comment by Beadd** [comment]
试了很多次没涨应该就是VIP或者灰色歌曲了，会有红色弹窗提示，可以试试老版本https://github.com/Beadd/Creamplayer/releases/tag/v2.6.1

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
