### ISSUE TITLE
flac格式内置专辑名称这块有点小bug

### ISSUE THREAD

**Issue by XuczSnow** [Beadd/Creamplayer#64]
![image](https://github.com/Beadd/Creamplayer/assets/37571254/6e1953f8-6023-4cf3-b264-f9e21732ab0d)

**Comment by Beadd** [comment]
具体是哪里有问题呢？

**Comment by XuczSnow** [comment]
这块笔误了，内置专利封面写成artist了

**Comment by Beadd** [comment]
感谢，已修正
