### ISSUE TITLE
专辑下载功能有吗

### ISSUE THREAD

**Issue by joesn-yzc** [Beadd/Creamplayer#65]
我发现输入专辑链接，或者我将一个专辑创建成歌单，就不能正常下载，我已经输入了VIP Cookie，如下面两个实例：
专辑创建成歌单：https://music.163.com/playlist?id=987127
专辑：https://music.163.com/album?id=82106346

**Comment by joesn-yzc** [comment]
开发者模式看，是报操作频繁，不确认是什么原因导致
![image](https://github.com/Beadd/Creamplayer/assets/5296186/a071fbb4-e1e5-48fd-bb06-1eda5e66d3ca)

**Comment by Beadd** [comment]
https://music.163.com/playlist?id=987127 这个歌单我实测是可以下载的，只不过里面只有一首非VIP歌曲，下载VIP的话需要填入已经是VIP的账号的Cookie，专辑下载的话你可以用老版本 https://github.com/Beadd/Creamplayer/releases/tag/v2.6.1

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
