### ISSUE TITLE
为什么这个歌单按回车之后没有反应呢？

### ISSUE THREAD

**Issue by Geeksun2018** [Beadd/Creamplayer#66]
https://y.qq.com/n/ryqq/playlist/2727950271

**Comment by Beadd** [comment]
新版本目前不支持QQ音乐，可以用老版本 https://github.com/Beadd/Creamplayer/releases/tag/v2.6.1

**Comment by Geeksun2018** [comment]
> 新版本目前不支持QQ音乐，可以用老版本 https://github.com/Beadd/Creamplayer/releases/tag/v2.6.1

好的，感谢！
