### ISSUE TITLE
不管下什么歌都是显示这个

### ISSUE THREAD

**Issue by wildcanyon** [Beadd/Creamplayer#67]
![微信图片_20240815203552](https://github.com/user-attachments/assets/c3759715-2e5c-4102-8c16-baad1c2f6fab)

**Comment by Beadd** [comment]
试了即便确实会有出现这个问题，不过歌曲还是可以下载的，可能是网易云返回的数据变了，过不了多久我会重修这个项目的

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
