### ISSUE TITLE
歌单下载不全

### ISSUE THREAD

**Issue by yangwenjie1231** [Beadd/Creamplayer#69]
https://music.163.com/#/playlist?id=2575711792
此歌单只能下载前4首，无法下完

**Comment by Beadd** [comment]
> https://music.163.com/#/playlist?id=2575711792 此歌单只能下载前4首，无法下完

实测除了5首VIP歌曲其余115首都可以下载，可能是你今天下载的歌曲太多了，可以明天再试试

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
