### ISSUE TITLE
请问怎么设置下载码率？

### ISSUE THREAD

**Issue by Beadd** [Beadd/Creamplayer#71]
请问怎么设置下载码率？

_Originally posted by @nyyjshcz in https://github.com/Beadd/Creamplayer/issues/61#issuecomment-2453954121_

**Comment by Beadd** [comment]
不好意思，刚刚说的有问题。在relases里面有两个版本，一个是正常版，用它即可，默认最高音质，填入了VIP cookie后会自动下载flac格式无损音乐；一个是强制360k音质版本（用来防止填入了VIP cookie后下载的无损歌曲太大），没有填入VIP cookie的话360k音质是最高的。

**Comment by nyyjshcz** [comment]
谢谢您，祝您高考顺利，来自高一的蒟蒻

**Comment by Beadd** [comment]
感谢感谢，但我已经大一了，也祝你高考顺利（虽然有点早）

**Comment by s1805948721** [comment]
加油

**Comment by Beadd** [comment]
已更新，[v5.0.0](https://github.com/Beadd/Creamplayer/releases/tag/v5.0.0)
